### POST Auth - sign-up
POST http://localhost:3001/api/v1/auth/sign-up
Content-Type: application/json

{
    "name": "Juan",
    "lastName": "Pérez",
    "email": "juan.perez@example.com",
    "password": "supersecurepassword",
    "roleId": 1
}

###

### POST Auth - sign-in
POST http://localhost:3001/api/v1/auth/sign-in
Content-Type: application/json

{
    "email": "juan.perez@example.com",
    "password": "supersecurepassword"
}

###

### PUT Admin - change-password-user
PUT http://localhost:3001/api/v1/admin/change-password-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzZTE2MzRjLWYwYTktNGFiZS1hZTdkLTcyZjkzOTQ2NjMyOSIsIm5hbWUiOiJKdWFuIiwibGFzdE5hbWUiOiJQw6lyZXoiLCJlbWFpbCI6Imp1YW4ucGVyZXpAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6dHJ1ZSwicm9sZUlkIjoxLCJpYXQiOjE3MjM4MTcwMDUsImV4cCI6MTcyMzgyOTYwNX0.LqvAoa30WwbZLW-BkAnfoqFsbuu88ViQiEuN2qvQoHk

{
  "email": "juan.perez@example.com",
  "newPassword": "supersecurepassword1"
}

###
