### POST Auth - sign-up
POST http://localhost:3001/api/v1/auth/sign-up
Content-Type: application/json

{
    "name": "Juan3",
    "lastName": "Pérez3",
    "email": "juan.perez6@example.com",
    "password": "supersecurepassword",
    "roleId": 1
}

###

### POST Auth - sign-in
POST http://localhost:3001/api/v1/auth/sign-in
Content-Type: application/json

{
    "email": "juan.perez@example.com",
    "password": "supersecurepassword1"
}

###

### PUT Admin - reset-password
PUT http://localhost:3001/api/v1/admin/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkyMDk1OWRiLWM0ZmUtNDgyZS04M2JmLWVhNGZjZTA4YzIxNSIsIm5hbWUiOiJKdWFuIiwibGFzdE5hbWUiOiJQw6lyZXoiLCJlbWFpbCI6Imp1YW4ucGVyZXpAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6ZmFsc2UsInJvbGVJZCI6MSwiaWF0IjoxNzI1MTQyNTgwLCJleHAiOjE3MjUxNTUxODB9.SSnZUVybjgdxvk7vtJUmNsmgXzV3YjOxBRBFTNBbqQo

{
  "email": "juan.perez2@example.com",
  "newPassword": "supersecurepassword1"
}

###

### GET Users - usersList
GET http://localhost:3001/api/v1/users?page=1&count=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkyMDk1OWRiLWM0ZmUtNDgyZS04M2JmLWVhNGZjZTA4YzIxNSIsIm5hbWUiOiJKdWFuIiwibGFzdE5hbWUiOiJQw6lyZXoiLCJlbWFpbCI6Imp1YW4ucGVyZXpAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6ZmFsc2UsInJvbGVJZCI6MSwiaWF0IjoxNzI1OTI0NTY0LCJleHAiOjE3MjU5MzcxNjR9.9bcahq1iZZtHLjscoWlCVm0HheWcOnaipxo4TWc5rgE

###

### GET Users - getUserById
GET http://localhost:3001/api/v1/users/6e57ff4e-c5ce-40a5-b7e6-126bd601ba39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljOWNjNmEyLTA4MTQtNDUyNC04ZWI1LTVhZWZjM2Q1Nzk5YiIsIm5hbWUiOiJKdWFuMiIsImxhc3ROYW1lIjoiUMOpcmV6MiIsImVtYWlsIjoianVhbi5wZXJlejJAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6dHJ1ZSwicm9sZUlkIjoxLCJpYXQiOjE3MjM4Mzg1NDAsImV4cCI6MTcyMzg1MTE0MH0.f6gdJM_u-wRS7lmig2NwpRNIIUWRn0orQtHMTmK2lzg

###

### POST Users - updateUser
POST http://localhost:3001/api/v1/users/update/9c9cc6a2-0814-4524-8eb5-5aefc3d5799b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljOWNjNmEyLTA4MTQtNDUyNC04ZWI1LTVhZWZjM2Q1Nzk5YiIsIm5hbWUiOiJKdWFuMiIsImxhc3ROYW1lIjoiUMOpcmV6MiIsImVtYWlsIjoianVhbi5wZXJlejJAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6dHJ1ZSwicm9sZUlkIjoxLCJpYXQiOjE3MjM4Mzg1NDAsImV4cCI6MTcyMzg1MTE0MH0.f6gdJM_u-wRS7lmig2NwpRNIIUWRn0orQtHMTmK2lzg

{
    "name": "JuanA",
    "lastName": "PérezA",
    "email": "juan.perezAzX@example.com",
    "roleId": 2
}
###

### PATCH Users - change-password
PATCH http://localhost:3001/api/v1/users/change-password/76cea5b8-30e6-4207-bf26-34bf18df2da7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2Y2VhNWI4LTMwZTYtNDIwNy1iZjI2LTM0YmYxOGRmMmRhNyIsIm5hbWUiOiJKdWFuIiwibGFzdE5hbWUiOiJQw6lyZXoiLCJlbWFpbCI6Imp1YW4ucGVyZXoyQGV4YW1wbGUuY29tIiwiY2hhbmdlUGFzc3dvcmQiOnRydWUsInJvbGVJZCI6MSwiaWF0IjoxNzI0Mzc4MDc0LCJleHAiOjE3MjQzOTA2NzR9.CC4_V7LTQIqgMK0VJKvsZhKZ59Ht5Wn4e-EWShXPwt0

{
    "temporaryPassword": "supersecurepassword",
    "newPassword": "supersecurepassword2ss"
}
###

### DELETE Users - deleteUser
DELETE http://localhost:3001/api/v1/users/delete/9c9cc6a2-0814-4524-8eb5-5aefc3d5799b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjljOWNjNmEyLTA4MTQtNDUyNC04ZWI1LTVhZWZjM2Q1Nzk5YiIsIm5hbWUiOiJKdWFuMiIsImxhc3ROYW1lIjoiUMOpcmV6MiIsImVtYWlsIjoianVhbi5wZXJlejJAZXhhbXBsZS5jb20iLCJjaGFuZ2VQYXNzd29yZCI6dHJ1ZSwicm9sZUlkIjoxLCJpYXQiOjE3MjM4Mzg1NDAsImV4cCI6MTcyMzg1MTE0MH0.f6gdJM_u-wRS7lmig2NwpRNIIUWRn0orQtHMTmK2lzg

###
